version: "3.9"

services:
  db:
    image: postgres:17-alpine
    container_name: batallaFriki-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: diego
      POSTGRES_DB: batallaFriki
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: batallaFriki-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:diego@db:5432/batallaFriki?schema=public
    depends_on:
      - db

  frontend:
    build:
      context: ./socket-client-ts
    container_name: batallaFriki-frontend
    restart: always
    ports:
      - "5173:4173"
    environment:
      VITE_API_URL: http://localhost:3000
    depends_on:
      - backend

  studio:
    build: .
    container_name: batallaFriki-studio
    command: npx prisma studio --port 5555 --browser none
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: postgresql://postgres:diego@db:5432/batallaFriki?schema=public
    depends_on:
      - db

volumes:
  db_data:
